name = "DigitalHubTalks2019"
uuid = "05ea51ae-fbc9-11e9-2319-f90bafdf26e0"
authors = ["Paulito Palmes <ppalmes@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
DataVoyager = "5721bf48-af8e-5845-8445-c9e18126e773"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ExcelFiles = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"
Feather = "becb17da-46f6-5d3c-ad1b-1c5fe96bc73c"
FeatherFiles = "b675d258-116a-5741-b937-b79f054b0542"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
Knet = "1902f260-5fb4-5aff-8c31-6271790ab950"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
MLDataUtils = "cc2ba9b6-d476-5e6d-8eaf-a92d5412d41d"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
ParquetFiles = "46a55296-af5a-53b0-aaa0-97023b66127f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TSML = "198dc43e-9e51-5cd7-9d40-d9794d335912"
TSMLextra = "0c7047ce-818d-11e9-1109-0323cd70e08d"
TensorFlow = "1d978283-2c37-5f34-9a8e-e9c0ece82495"
VegaDatasets = "0ae4a718-28b7-58ec-9efb-cded64d6d5b4"

[compat]
julia = "1"
